export const defaultRecipes = [
  {
    id: 1,
    title: "Kyllinggryte med ris",
    description: "En enkel og proteinrik meal prep-rett som passer godt til flere dager.",
    time: 40,
    portions: 4,
    calories: 650,
    protein: 48,
    carbs: 70,
    fat: 18,
    tags: ["proteinrik", "meal prep"],
    ingredients: [
      { name: "Kyllingfilet", amount: 800, unit: "g" },
      { name: "Ris", amount: 300, unit: "g" },
      { name: "Grønnsaksblanding", amount: 400, unit: "g" },
      { name: "Lett crème fraîche", amount: 200, unit: "g" },
    ],
    instructions: [
      "Kok risen etter anvisning på pakken.",
      "Skjær kyllingen i biter og stek den i en stor panne.",
      "Tilsett grønnsaker og crème fraîche.",
      "La alt småkoke i noen minutter.",
      "Fordel retten i matbokser.",
    ],
    prepNote: "Holder seg fint i kjøleskapet i 3–4 dager.",
  },
  {
    id: 2,
    title: "Tacobowl med karbonadedeig",
    description: "En rask og enkel tacobowl med mye smak og god mengde protein.",
    time: 30,
    portions: 4,
    calories: 590,
    protein: 42,
    carbs: 55,
    fat: 20,
    tags: ["proteinrik", "rask"],
    ingredients: [
      { name: "Karbonadedeig", amount: 600, unit: "g" },
      { name: "Ris", amount: 280, unit: "g" },
      { name: "Mais", amount: 1, unit: "boks" },
      { name: "Salsa", amount: 200, unit: "g" },
      { name: "Tacokrydder", amount: 1, unit: "pose" },
    ],
    instructions: [
      "Kok risen.",
      "Stek karbonadedeig med tacokrydder.",
      "Fordel ris, kjøtt, mais og salsa i bokser.",
      "Topp med ønsket tilbehør ved servering.",
    ],
    prepNote: "Passer godt til lunsj eller middag gjennom uka.",
  },
  {
    id: 3,
    title: "Protein overnight oats",
    description: "En enkel frokost du kan lage kvelden før og ha klar i kjøleskapet.",
    time: 10,
    portions: 3,
    calories: 430,
    protein: 34,
    carbs: 48,
    fat: 11,
    tags: ["lavkalori", "student", "rask"],
    ingredients: [
      { name: "Havregryn", amount: 180, unit: "g" },
      { name: "Gresk yoghurt", amount: 450, unit: "g" },
      { name: "Proteinmelk", amount: 300, unit: "ml" },
      { name: "Proteinpulver", amount: 60, unit: "g" },
      { name: "Bær", amount: 150, unit: "g" },
    ],
    instructions: [
      "Bland havregryn, yoghurt, melk og proteinpulver.",
      "Fordel blandingen i glass eller bokser.",
      "Topp med bær.",
      "Sett i kjøleskapet over natten.",
    ],
    prepNote: "Perfekt som rask frokost i 2–3 dager.",
  },
  {
    id: 4,
    title: "Laksebowl med grønnsaker",
    description: "En mettende bowl med laks, ris og grønnsaker.",
    time: 35,
    portions: 3,
    calories: 720,
    protein: 39,
    carbs: 62,
    fat: 31,
    tags: ["meal prep"],
    ingredients: [
      { name: "Laksefilet", amount: 600, unit: "g" },
      { name: "Ris", amount: 240, unit: "g" },
      { name: "Brokkoli", amount: 300, unit: "g" },
      { name: "Gulrot", amount: 3, unit: "stk" },
      { name: "Soyasaus", amount: 3, unit: "ss" },
    ],
    instructions: [
      "Kok risen.",
      "Stek eller bak laksen.",
      "Damp eller stek grønnsakene.",
      "Fordel alt i matbokser og topp med soyasaus.",
    ],
    prepNote: "Best de første 2–3 dagene.",
  },
  {
    id: 5,
    title: "Kremet kyllingpasta",
    description: "En studentvennlig pastarett som gir mange porsjoner.",
    time: 35,
    portions: 5,
    calories: 680,
    protein: 45,
    carbs: 75,
    fat: 19,
    tags: ["proteinrik", "student", "budsjett"],
    ingredients: [
      { name: "Kyllingfilet", amount: 900, unit: "g" },
      { name: "Pasta", amount: 500, unit: "g" },
      { name: "Lett matfløte", amount: 300, unit: "ml" },
      { name: "Spinat", amount: 150, unit: "g" },
      { name: "Revet ost", amount: 100, unit: "g" },
    ],
    instructions: [
      "Kok pastaen.",
      "Stek kyllingen i biter.",
      "Tilsett matfløte, spinat og ost.",
      "Bland inn pastaen.",
      "Fordel i fem porsjoner.",
    ],
    prepNote: "Veldig fin å lage i stor porsjon.",
  },
  {
    id: 6,
    title: "Egg- og potetform",
    description: "Billig, enkel og mettende meal prep med få ingredienser.",
    time: 45,
    portions: 4,
    calories: 510,
    protein: 31,
    carbs: 44,
    fat: 22,
    tags: ["budsjett", "student"],
    ingredients: [
      { name: "Egg", amount: 8, unit: "stk" },
      { name: "Poteter", amount: 700, unit: "g" },
      { name: "Cottage cheese", amount: 300, unit: "g" },
      { name: "Paprika", amount: 2, unit: "stk" },
      { name: "Revet ost", amount: 80, unit: "g" },
    ],
    instructions: [
      "Kok potetene til de nesten er møre.",
      "Visp sammen egg og cottage cheese.",
      "Legg poteter og paprika i en ildfast form.",
      "Hell over eggeblandingen og topp med ost.",
      "Stek formen til den har satt seg.",
    ],
    prepNote: "Kan spises både varm og kald.",
  },
];